window.NX_I18N={
  id:{label:"Indonesia",dir:"ltr",nav:{dashboard:"Dashboard",companies:"Perusahaan",projects:"Project",repositories:"Repository",health:"Kesehatan Sistem",sources:"Sumber Scraper",roadmap:"Roadmap",calendar:"Kalender",milestones:"Milestone",tasks:"Tugas",reports:"Laporan",risks:"Risiko",budget:"Anggaran",documents:"Dokumen",decisions:"Keputusan",notifications:"Notifikasi",team:"Tim",activity:"Aktivitas",settings:"Pengaturan"},common:{login:"Masuk",register:"Daftar",logout:"Keluar",account:"Akun",language:"Bahasa",theme:"Tema",system:"Sistem",light:"Terang",dark:"Gelap",reducedMotion:"Kurangi animasi",autoRefresh:"Pembaruan otomatis",save:"Simpan",cancel:"Batal",close:"Tutup",email:"Email",password:"Password",name:"Nama",google:"Lanjutkan dengan Google",forgot:"Lupa password?",back:"Kembali",loading:"Memuat...",configured:"Terkonfigurasi",notConfigured:"Belum dikonfigurasi",profile:"Profil",security:"Keamanan",appearance:"Tampilan",preferences:"Preferensi"}},
  en:{label:"English",dir:"ltr",nav:{dashboard:"Dashboard",companies:"Companies",projects:"Projects",repositories:"Repositories",health:"System Health",sources:"Scraper Sources",roadmap:"Roadmap",calendar:"Calendar",milestones:"Milestones",tasks:"Tasks",reports:"Reports",risks:"Risks",budget:"Budget",documents:"Documents",decisions:"Decisions",notifications:"Notifications",team:"Team",activity:"Activity",settings:"Settings"},common:{login:"Sign in",register:"Register",logout:"Sign out",account:"Account",language:"Language",theme:"Theme",system:"System",light:"Light",dark:"Dark",reducedMotion:"Reduce animation",autoRefresh:"Auto refresh",save:"Save",cancel:"Cancel",close:"Close",email:"Email",password:"Password",name:"Name",google:"Continue with Google",forgot:"Forgot password?",back:"Back",loading:"Loading...",configured:"Configured",notConfigured:"Not configured",profile:"Profile",security:"Security",appearance:"Appearance",preferences:"Preferences"}},
  ms:{label:"Melayu",dir:"ltr",nav:{dashboard:"Papan Pemuka",companies:"Syarikat",projects:"Projek",repositories:"Repositori",health:"Kesihatan Sistem",sources:"Sumber Scraper",roadmap:"Roadmap",calendar:"Kalendar",milestones:"Milestone",tasks:"Tugas",reports:"Laporan",risks:"Risiko",budget:"Belanjawan",documents:"Dokumen",decisions:"Keputusan",notifications:"Notifikasi",team:"Pasukan",activity:"Aktiviti",settings:"Tetapan"},common:{login:"Log masuk",register:"Daftar",logout:"Log keluar",account:"Akaun",language:"Bahasa",theme:"Tema",system:"Sistem",light:"Cerah",dark:"Gelap",reducedMotion:"Kurangkan animasi",autoRefresh:"Muat semula automatik",save:"Simpan",cancel:"Batal",close:"Tutup",email:"E-mel",password:"Kata laluan",name:"Nama",google:"Teruskan dengan Google",forgot:"Lupa kata laluan?",back:"Kembali",loading:"Memuatkan...",configured:"Dikonfigurasi",notConfigured:"Belum dikonfigurasi",profile:"Profil",security:"Keselamatan",appearance:"Paparan",preferences:"Keutamaan"}},
  vi:{label:"Tiếng Việt",dir:"ltr",nav:{dashboard:"Tổng quan",companies:"Công ty",projects:"Dự án",repositories:"Kho mã",health:"Sức khỏe hệ thống",sources:"Nguồn Scraper",roadmap:"Lộ trình",calendar:"Lịch",milestones:"Cột mốc",tasks:"Nhiệm vụ",reports:"Báo cáo",risks:"Rủi ro",budget:"Ngân sách",documents:"Tài liệu",decisions:"Quyết định",notifications:"Thông báo",team:"Đội ngũ",activity:"Hoạt động",settings:"Cài đặt"},common:{login:"Đăng nhập",register:"Đăng ký",logout:"Đăng xuất",account:"Tài khoản",language:"Ngôn ngữ",theme:"Giao diện",system:"Hệ thống",light:"Sáng",dark:"Tối",reducedMotion:"Giảm hoạt ảnh",autoRefresh:"Tự động cập nhật",save:"Lưu",cancel:"Hủy",close:"Đóng",email:"Email",password:"Mật khẩu",name:"Tên",google:"Tiếp tục với Google",forgot:"Quên mật khẩu?",back:"Quay lại",loading:"Đang tải...",configured:"Đã cấu hình",notConfigured:"Chưa cấu hình",profile:"Hồ sơ",security:"Bảo mật",appearance:"Hiển thị",preferences:"Tùy chọn"}},
  th:{label:"ไทย",dir:"ltr",nav:{dashboard:"แดชบอร์ด",companies:"บริษัท",projects:"โครงการ",repositories:"รีโพสิตอรี",health:"สุขภาพระบบ",sources:"แหล่ง Scraper",roadmap:"โรดแมป",calendar:"ปฏิทิน",milestones:"หมุดหมาย",tasks:"งาน",reports:"รายงาน",risks:"ความเสี่ยง",budget:"งบประมาณ",documents:"เอกสาร",decisions:"การตัดสินใจ",notifications:"การแจ้งเตือน",team:"ทีม",activity:"กิจกรรม",settings:"การตั้งค่า"},common:{login:"เข้าสู่ระบบ",register:"สมัครสมาชิก",logout:"ออกจากระบบ",account:"บัญชี",language:"ภาษา",theme:"ธีม",system:"ระบบ",light:"สว่าง",dark:"มืด",reducedMotion:"ลดแอนิเมชัน",autoRefresh:"รีเฟรชอัตโนมัติ",save:"บันทึก",cancel:"ยกเลิก",close:"ปิด",email:"อีเมล",password:"รหัสผ่าน",name:"ชื่อ",google:"ดำเนินการต่อด้วย Google",forgot:"ลืมรหัสผ่าน?",back:"กลับ",loading:"กำลังโหลด...",configured:"กำหนดค่าแล้ว",notConfigured:"ยังไม่ได้กำหนดค่า",profile:"โปรไฟล์",security:"ความปลอดภัย",appearance:"การแสดงผล",preferences:"การตั้งค่า"}},
  zh:{label:"简体中文",dir:"ltr",nav:{dashboard:"仪表板",companies:"公司",projects:"项目",repositories:"代码库",health:"系统健康",sources:"抓取来源",roadmap:"路线图",calendar:"日历",milestones:"里程碑",tasks:"任务",reports:"报告",risks:"风险",budget:"预算",documents:"文档",decisions:"决策",notifications:"通知",team:"团队",activity:"活动",settings:"设置"},common:{login:"登录",register:"注册",logout:"退出",account:"账户",language:"语言",theme:"主题",system:"系统",light:"浅色",dark:"深色",reducedMotion:"减少动画",autoRefresh:"自动刷新",save:"保存",cancel:"取消",close:"关闭",email:"邮箱",password:"密码",name:"姓名",google:"使用 Google 继续",forgot:"忘记密码？",back:"返回",loading:"加载中...",configured:"已配置",notConfigured:"未配置",profile:"个人资料",security:"安全",appearance:"外观",preferences:"偏好设置"}},
  ja:{label:"日本語",dir:"ltr",nav:{dashboard:"ダッシュボード",companies:"会社",projects:"プロジェクト",repositories:"リポジトリ",health:"システム状態",sources:"スクレイパー",roadmap:"ロードマップ",calendar:"カレンダー",milestones:"マイルストーン",tasks:"タスク",reports:"レポート",risks:"リスク",budget:"予算",documents:"ドキュメント",decisions:"意思決定",notifications:"通知",team:"チーム",activity:"アクティビティ",settings:"設定"},common:{login:"ログイン",register:"登録",logout:"ログアウト",account:"アカウント",language:"言語",theme:"テーマ",system:"システム",light:"ライト",dark:"ダーク",reducedMotion:"アニメーションを減らす",autoRefresh:"自動更新",save:"保存",cancel:"キャンセル",close:"閉じる",email:"メール",password:"パスワード",name:"名前",google:"Googleで続行",forgot:"パスワードを忘れた？",back:"戻る",loading:"読み込み中...",configured:"設定済み",notConfigured:"未設定",profile:"プロフィール",security:"セキュリティ",appearance:"外観",preferences:"設定"}},
  ko:{label:"한국어",dir:"ltr",nav:{dashboard:"대시보드",companies:"회사",projects:"프로젝트",repositories:"저장소",health:"시스템 상태",sources:"스크래퍼 소스",roadmap:"로드맵",calendar:"캘린더",milestones:"마일스톤",tasks:"작업",reports:"보고서",risks:"위험",budget:"예산",documents:"문서",decisions:"의사결정",notifications:"알림",team:"팀",activity:"활동",settings:"설정"},common:{login:"로그인",register:"회원가입",logout:"로그아웃",account:"계정",language:"언어",theme:"테마",system:"시스템",light:"라이트",dark:"다크",reducedMotion:"애니메이션 줄이기",autoRefresh:"자동 새로고침",save:"저장",cancel:"취소",close:"닫기",email:"이메일",password:"비밀번호",name:"이름",google:"Google로 계속",forgot:"비밀번호를 잊으셨나요?",back:"뒤로",loading:"로드 중...",configured:"구성됨",notConfigured:"구성되지 않음",profile:"프로필",security:"보안",appearance:"모양",preferences:"환경설정"}},
  ar:{label:"العربية",dir:"rtl",nav:{dashboard:"لوحة التحكم",companies:"الشركات",projects:"المشاريع",repositories:"المستودعات",health:"صحة النظام",sources:"مصادر الكاشط",roadmap:"خارطة الطريق",calendar:"التقويم",milestones:"المراحل",tasks:"المهام",reports:"التقارير",risks:"المخاطر",budget:"الميزانية",documents:"المستندات",decisions:"القرارات",notifications:"الإشعارات",team:"الفريق",activity:"النشاط",settings:"الإعدادات"},common:{login:"تسجيل الدخول",register:"إنشاء حساب",logout:"تسجيل الخروج",account:"الحساب",language:"اللغة",theme:"السمة",system:"النظام",light:"فاتح",dark:"داكن",reducedMotion:"تقليل الحركة",autoRefresh:"تحديث تلقائي",save:"حفظ",cancel:"إلغاء",close:"إغلاق",email:"البريد الإلكتروني",password:"كلمة المرور",name:"الاسم",google:"المتابعة باستخدام Google",forgot:"هل نسيت كلمة المرور؟",back:"رجوع",loading:"جارٍ التحميل...",configured:"تم الإعداد",notConfigured:"غير مُعد",profile:"الملف الشخصي",security:"الأمان",appearance:"المظهر",preferences:"التفضيلات"}},
  es:{label:"Español",dir:"ltr",nav:{dashboard:"Panel",companies:"Empresas",projects:"Proyectos",repositories:"Repositorios",health:"Salud del sistema",sources:"Fuentes del scraper",roadmap:"Hoja de ruta",calendar:"Calendario",milestones:"Hitos",tasks:"Tareas",reports:"Informes",risks:"Riesgos",budget:"Presupuesto",documents:"Documentos",decisions:"Decisiones",notifications:"Notificaciones",team:"Equipo",activity:"Actividad",settings:"Ajustes"},common:{login:"Iniciar sesión",register:"Registrarse",logout:"Cerrar sesión",account:"Cuenta",language:"Idioma",theme:"Tema",system:"Sistema",light:"Claro",dark:"Oscuro",reducedMotion:"Reducir animaciones",autoRefresh:"Actualización automática",save:"Guardar",cancel:"Cancelar",close:"Cerrar",email:"Correo",password:"Contraseña",name:"Nombre",google:"Continuar con Google",forgot:"¿Olvidaste la contraseña?",back:"Volver",loading:"Cargando...",configured:"Configurado",notConfigured:"No configurado",profile:"Perfil",security:"Seguridad",appearance:"Apariencia",preferences:"Preferencias"}}
};

Object.assign(window.NX_I18N.id.common,{newPassword:"Password baru",resendVerification:"Kirim ulang verifikasi"});
Object.assign(window.NX_I18N.en.common,{newPassword:"New password",resendVerification:"Resend verification"});
Object.assign(window.NX_I18N.ms.common,{newPassword:"Kata laluan baharu",resendVerification:"Hantar semula pengesahan"});
Object.assign(window.NX_I18N.vi.common,{newPassword:"Mật khẩu mới",resendVerification:"Gửi lại xác minh"});
Object.assign(window.NX_I18N.th.common,{newPassword:"รหัสผ่านใหม่",resendVerification:"ส่งการยืนยันอีกครั้ง"});
Object.assign(window.NX_I18N.zh.common,{newPassword:"新密码",resendVerification:"重新发送验证"});
Object.assign(window.NX_I18N.ja.common,{newPassword:"新しいパスワード",resendVerification:"確認メールを再送信"});
Object.assign(window.NX_I18N.ko.common,{newPassword:"새 비밀번호",resendVerification:"인증 메일 다시 보내기"});
Object.assign(window.NX_I18N.ar.common,{newPassword:"كلمة مرور جديدة",resendVerification:"إعادة إرسال التحقق"});
Object.assign(window.NX_I18N.es.common,{newPassword:"Nueva contraseña",resendVerification:"Reenviar verificación"});

Object.assign(window.NX_I18N.id.common,{confirmPassword:"Konfirmasi password",setPassword:"Tetapkan password",passwordTooShort:"Password minimal 8 karakter",passwordMismatch:"Password tidak sama",passwordUpdated:"Password berhasil diperbarui"});
Object.assign(window.NX_I18N.en.common,{confirmPassword:"Confirm password",setPassword:"Set password",passwordTooShort:"Password must contain at least 8 characters",passwordMismatch:"Passwords do not match",passwordUpdated:"Password updated successfully"});
Object.assign(window.NX_I18N.ms.common,{confirmPassword:"Sahkan kata laluan",setPassword:"Tetapkan kata laluan",passwordTooShort:"Kata laluan mesti sekurang-kurangnya 8 aksara",passwordMismatch:"Kata laluan tidak sepadan",passwordUpdated:"Kata laluan berjaya dikemas kini"});
Object.assign(window.NX_I18N.vi.common,{confirmPassword:"Xác nhận mật khẩu",setPassword:"Đặt mật khẩu",passwordTooShort:"Mật khẩu phải có ít nhất 8 ký tự",passwordMismatch:"Mật khẩu không khớp",passwordUpdated:"Đã cập nhật mật khẩu"});
Object.assign(window.NX_I18N.th.common,{confirmPassword:"ยืนยันรหัสผ่าน",setPassword:"ตั้งรหัสผ่าน",passwordTooShort:"รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร",passwordMismatch:"รหัสผ่านไม่ตรงกัน",passwordUpdated:"อัปเดตรหัสผ่านแล้ว"});
Object.assign(window.NX_I18N.zh.common,{confirmPassword:"确认密码",setPassword:"设置密码",passwordTooShort:"密码至少需要 8 个字符",passwordMismatch:"两次密码不一致",passwordUpdated:"密码已更新"});
Object.assign(window.NX_I18N.ja.common,{confirmPassword:"パスワードを確認",setPassword:"パスワードを設定",passwordTooShort:"パスワードは8文字以上必要です",passwordMismatch:"パスワードが一致しません",passwordUpdated:"パスワードを更新しました"});
Object.assign(window.NX_I18N.ko.common,{confirmPassword:"비밀번호 확인",setPassword:"비밀번호 설정",passwordTooShort:"비밀번호는 8자 이상이어야 합니다",passwordMismatch:"비밀번호가 일치하지 않습니다",passwordUpdated:"비밀번호가 업데이트되었습니다"});
Object.assign(window.NX_I18N.ar.common,{confirmPassword:"تأكيد كلمة المرور",setPassword:"تعيين كلمة المرور",passwordTooShort:"يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",passwordMismatch:"كلمتا المرور غير متطابقتين",passwordUpdated:"تم تحديث كلمة المرور بنجاح"});
Object.assign(window.NX_I18N.es.common,{confirmPassword:"Confirmar contraseña",setPassword:"Establecer contraseña",passwordTooShort:"La contraseña debe tener al menos 8 caracteres",passwordMismatch:"Las contraseñas no coinciden",passwordUpdated:"Contraseña actualizada correctamente"});

(function(){
  var saved=localStorage.getItem("nx-language");
  var fallback=window.NX_CONFIG&&window.NX_CONFIG.app&&window.NX_CONFIG.app.defaultLanguage||"id";
  window.NX_LANG=window.NX_I18N[saved]?saved:fallback;
  window.NX_T=function(key){
    var parts=String(key).split(".");
    var node=window.NX_I18N[window.NX_LANG]||window.NX_I18N.id;
    for(var i=0;i<parts.length;i++) node=node&&node[parts[i]];
    return node==null?key:String(node);
  };
})();
